### DISCUSSION TITLE
Publishing this extension to the Open VSX registry

### DISCUSSION THREAD

**Discussion by Clint-Chester** [forcedotcom/salesforcedx-vscode#3877] [Ideas]
Hey there! This is in reference to #2650, but since this isn't something that I can't just do a pull request for and need assistance from Salesforce, thought I'd detail the what, why and how of this idea so a discussion can be had 😄 

## What is the Open VSX registry
[Open VSX](https://open-vsx.org/) is an open-source registry for VS Code extensions. It can be used by any development environment that supports these extensions. Open VSX is operated by the Eclipse Foundation, in which [Salesforce is a proud supporter and partner](https://opensource.salesforce.com/) of.

## Why register this VS Code Extension with the Open VSX registry
Beyond the requests in the referenced issue (there's a few others in this repo), rather than talk about the merits of supporting the Open Source initiatives (which are definitely important) or why [Open VSX was created](https://outreach.eclipse.foundation/openvsx), the benefits are allowing wider adoption for developers using different IDEs and development platforms (with relatively low effort). It would allow support for IDEs and development platforms such as:
- [Gitpod](https://www.gitpod.io/)
- [Google Cloud Shell](https://cloud.google.com/shell)
- [VSCodium](https://vscodium.com/)
- [Eclipse Theia](https://theia-ide.org/)

I believe that supporting other IDEs and cloud based development platforms will not only help improve developer's individual experiences with how they build on the platform (onboarding experiences, tool familiarity etc.), but will be beneficial to enterprises making use of cloud based development platforms like Gitpod or Google Cloud Shell to help with overall developer activity.

## How to get this VS Code Extension on the Open VSX registry
There are [instructions here on how to register the extension](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) on Open VSX, but it boils down to two main steps of:
1. Using the Eclipse Foundation account (I'm assuming Salesforce would have) and signing the publisher agreement. Unfortunately something people who don't work for Salesforce can open a pull request for 😄 
2. Updating the packaging and registry deployment process to deploy to both the VS Code Marketplace and Open VSX Registry (someone created a [GitHub Action](https://github.com/HaaLeo/publish-vscode-extension#readme) for this). This is one I'd be happy to do a pull request for.

## Summary
It's something that would need Salesforce's assistance on signing agreements, but I think it would be a great way to help adopt the use of cloud based development platforms. It would allow large Salesforce Development teams to help improve development efficiencies and onboarding with standardised tooling, and also another simple way to show Salesforce's commitment to Open Source 😄 

Hope this was an interesting read and keen on people's thoughts, thanks!

**Comment by ghuntley** [comment]
👋 Geoff here from Gitpod. Supportive of seeing this extension being published. Let me know how I can help.

**Reply by RupertBarrow** [reply]
Hi Geoff, I opened the initial issue #2650 a year and a half ago.
The Salesforce extension pack is composed of multiple extensions, which all need to be published to the Open VSX Registry.

I started with the following .gitpod.yml file :

```
tasks:
  - init:    echo "Replace me with a build script for the project."
    command: echo "Replace me with something that should run on every start, or just remove me entirely."

# Dockerfile borrowed from https://github.com/forcedotcom/vscode-remote-try-sfdx/blob/master/.devcontainer/Dockerfile
image:
  file: .gitpod.Dockerfile

# See here for reference : https://github.com/forcedotcom/vscode-remote-try-sfdx/blob/master/.devcontainer/devcontainer.json
# Gitpod equivalent to SFDX VS Code remote development, VS code extensions
vscode:
  extensions:
    - salesforce.salesforcedx-vscode@48.16.0:vLu13WqhCXKGhh0YpzeZZA==
    - salesforce.salesforcedx-vscode-apex-replay-debugger@48.16.0:FucSxOENqBU7fqblXvDwRg==
    - salesforce.salesforcedx-vscode-apex-debugger@48.16.0:tMPgnL6WmEopf4lm3eqeyQ==
    - salesforce.salesforcedx-vscode-core@48.16.0:89dLoqo8QS0SMl35OGbCeQ==
    - salesforce.salesforcedx-vscode-visualforce@48.16.0:5d6musT54jdLrLl+Mc20yQ==
    - salesforce.salesforcedx-vscode-apex@48.16.0:dKpgUjCxBcj44Rf+HgHN/w==
    - dbaeumer.vscode-eslint@2.1.5:9Wg0Glx/TwD8ElFBg+FKcQ==
    - salesforce.salesforcedx-vscode-lightning@48.16.0:vg+fiApHuTi3Pt7V+qrb2Q==
    - esbenp.prettier-vscode@4.7.0:kgoYSh1LwTixKtJtQWtodQ==
    - redhat.vscode-xml@0.11.0:UisfuLs/74cHN6OonFG4YA==
```
and the associated .gitpod.Dockerfile :

```
FROM salesforce/salesforcedx:latest-slim
USER gitpod
```

I did not get anywhere significant 18 months ago.
Today, this crashes Gitpod, so I gave up : "Oh, no! Something went wrong!
cannot initialize workspace: cannot initialize workspace: no backup found; last backup failed: workspace does not exist."
![image](https://user-images.githubusercontent.com/48629751/160653560-a6285e96-d020-4af3-9076-d890df91db31.png)
